// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemasRecetas;

#nullable disable

namespace SistemasRecetas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251009021823_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SistemasRecetas.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IdMeal")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Thumb")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("SistemasRecetas.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("idMeal")
                        .HasColumnType("longtext");

                    b.Property<string>("strIngredient1")
                        .HasColumnType("longtext");

                    b.Property<string>("strIngredient10")
                        .HasColumnType("longtext");

                    b.Property<string>("strIngredient11")
                        .HasColumnType("longtext");

                    b.Property<string>("strIngredient12")
                        .HasColumnType("longtext");

                    b.Property<string>("strIngredient13")
                        .HasColumnType("longtext");

                    b.Property<string>("strIngredient14")
                        .HasColumnType("longtext");

                    b.Property<string>("strIngredient15")
                        .HasColumnType("longtext");

                    b.Property<string>("strIngredient16")
                        .HasColumnType("longtext");

                    b.Property<string>("strIngredient17")
                        .HasColumnType("longtext");

                    b.Property<string>("strIngredient18")
                        .HasColumnType("longtext");

                    b.Property<string>("strIngredient19")
                        .HasColumnType("longtext");

                    b.Property<string>("strIngredient2")
                        .HasColumnType("longtext");

                    b.Property<string>("strIngredient20")
                        .HasColumnType("longtext");

                    b.Property<string>("strIngredient3")
                        .HasColumnType("longtext");

                    b.Property<string>("strIngredient4")
                        .HasColumnType("longtext");

                    b.Property<string>("strIngredient5")
                        .HasColumnType("longtext");

                    b.Property<string>("strIngredient6")
                        .HasColumnType("longtext");

                    b.Property<string>("strIngredient7")
                        .HasColumnType("longtext");

                    b.Property<string>("strIngredient8")
                        .HasColumnType("longtext");

                    b.Property<string>("strIngredient9")
                        .HasColumnType("longtext");

                    b.Property<string>("strInstructions")
                        .HasColumnType("longtext");

                    b.Property<string>("strMeal")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("strMealThumb")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
